#!/usr/bin/env bash
# gen-usage.sh - print the usage reference (docs/usage.md) built from each script's --help
#
#   tools/gen-usage.sh > docs/usage.md
#
# tests/test_docs.sh fails when docs/usage.md no longer matches, so the reference
# cannot drift from the scripts.
set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)

echo "# Usage reference"
echo
echo "Generated by \`tools/gen-usage.sh\` from each script's \`--help\`. Do not edit by hand."

for script in "$root"/bin/*.sh; do
    echo
    echo "## $(basename "$script")"
    echo
    echo '```'
    bash "$script" --help
    echo '```'
done
